package candyBar.myBatis.dao;

import candyBar.myBatis.model.SourceContract;
import java.util.List;

public interface SourceContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SOURCE_CONTRACT
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SOURCE_CONTRACT
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    int insert(SourceContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SOURCE_CONTRACT
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    SourceContract selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SOURCE_CONTRACT
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    List<SourceContract> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SOURCE_CONTRACT
     *
     * @mbg.generated Sun Apr 06 16:09:44 EEST 2025
     */
    int updateByPrimaryKey(SourceContract record);
}